require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-graphql
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*.rb
    - vendor/**/*

Style/Documentation:
  Exclude:
    - config/application.rb
