name: Lint & run tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
defaults:
  run:
    working-directory: api
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby & gems
        uses: ruby/setup-ruby@v1.100.1
        with:
          working-directory: api
          bundler-cache: true

      - name: Lint Ruby files
        run: bundler exec rubocop --parallel --format github
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: invoicr_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby & gems
        uses: ruby/setup-ruby@v1.100.1
        with:
          working-directory: api
          bundler-cache: true

      - name: Setup databases
        run: bundle exec rails parallel:setup

      - name: Run tests
        run: bundle exec rails parallel:spec
